{
 "title": "Flagger Canary Status",
 "description": "Watch the status of your canary deployments via Flagger. Source was Flagger's dashboard available in Github, but which was updated 3 years ago and needed a bunch of refactoring to modern Prometheus & Grafana. Also added various improvements.",
 "tags": [
  "start here",
  "flagger",
  "canary rollouts"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "awsaccount",
    "label": "AWS Account",
    "query": {
     "query": "query_result(avg(kube_deployment_labels) by (account))"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "query_result(avg(kube_deployment_labels{account=~\"$awsaccount\"}) by (cluster))"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(avg(kube_deployment_labels{cluster=~\"$cluster\"}) by (namespace))"
    }
   },
   {
    "name": "canary",
    "label": "Workload",
    "query": {
     "query": "query_result((avg(kube_deployment_labels{namespace=~\"$namespace\",deployment!~\".*primary.*\"}) by (deployment)) or (avg(kube_statefulset_labels{namespace=~\"$namespace\",statefulset!~\".*primary.*\"}) by (statefulset)))"
    }
   },
   {
    "name": "primary",
    "label": "Primary",
    "query": {
     "query": "query_result((avg(kube_deployment_labels{namespace=~\"$namespace\",deployment=~\"$canary-primary\"}) by (deployment)) or (avg(kube_statefulset_labels{namespace=~\"$namespace\",statefulset=~\"$canary-primary\"}) by (statefulset)))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Flagger Rollout Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Primary: Flagger Weighting",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "flagger_canary_weight{namespace=\"test\",workload=\"podinfo-primary\", app=\"flagger\"}",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Canary: Flagger Weighting",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "flagger_canary_weight{namespace=\"test\",workload=\"podinfo\", app=\"flagger\"}",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Flagger Canary: Last Result",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(\n      http_requests_total{\n        namespace=\"test\",\n        app=\"podinfo\",\n      }[30s]\n    )",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Requests, Error, Duration (RED) - Only usable for Istio-enabled Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Primary: Incoming Request Volume",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "round(sum by (cluster)(rate(istio_requests_total{reporter=\"destination\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$primary\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])), 0.001)",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "Primary: Incoming Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (cluster)(irate(istio_requests_total{reporter=\"destination\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$primary\",response_code!~\"5.*\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) / sum by (cluster)(irate(istio_requests_total{reporter=\"destination\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$primary\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "Canary: Incoming Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (cluster)(irate(istio_requests_total{reporter=\"destination\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$canary\",response_code!~\"5.*\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) / sum by (cluster)(irate(istio_requests_total{reporter=\"destination\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$canary\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "Canary: Incoming Request Volume",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "round(sum by (cluster)(rate(istio_requests_total{reporter=\"destination\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$canary\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])), 0.001)",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "Primary: Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$primary\", destination_workload_namespace=~\"$namespace\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster,le)) / 1000",
       "legendFormat": "P50 ({{ cluster }})"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$primary\", destination_workload_namespace=~\"$namespace\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster,le)) / 1000",
       "legendFormat": "P90 ({{ cluster }})"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$primary\", destination_workload_namespace=~\"$namespace\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster,le)) / 1000",
       "legendFormat": "P95 ({{ cluster }})"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$primary\", destination_workload_namespace=~\"$namespace\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster,le)) / 1000",
       "legendFormat": "P99 ({{ cluster }})"
      }
     ]
    },
    {
     "title": "Canary: Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$canary\", destination_workload_namespace=~\"$namespace\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster,le)) / 1000",
       "legendFormat": "P50 ({{ cluster }})"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$canary\", destination_workload_namespace=~\"$namespace\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster,le)) / 1000",
       "legendFormat": "P90 ({{ cluster }})"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$canary\", destination_workload_namespace=~\"$namespace\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster,le)) / 1000",
       "legendFormat": "P95 ({{ cluster }})"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",destination_workload=~\"$canary\", destination_workload_namespace=~\"$namespace\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster,le)) / 1000",
       "legendFormat": "P99 ({{ cluster }})"
      }
     ]
    },
    {
     "title": "Primary: Incoming Requests by Source And Response Code",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$primary\", reporter=\"destination\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster,source_workload, source_workload_namespace, response_code), 0.001)",
       "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }} (?mTLS) ({{ cluster }})"
      },
      {
       "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$primary\", reporter=\"destination\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster,source_workload, source_workload_namespace, response_code), 0.001)",
       "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }} ({{ cluster }})"
      }
     ]
    },
    {
     "title": "Canary: Incoming Requests by Source And Response Code",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$canary\", reporter=\"destination\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster,source_workload, source_workload_namespace, response_code), 0.001)",
       "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }} (?mTLS) ({{ cluster }})"
      },
      {
       "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$canary\", reporter=\"destination\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster,source_workload, source_workload_namespace, response_code), 0.001)",
       "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }} ({{ cluster }})"
      }
     ]
    },
    {
     "title": "Primary: Outgoing Requests by Destination And Response Code",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$primary\", reporter=\"source\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster,destination_service, response_code), 0.001)",
       "legendFormat": "{{ destination_service }} : {{ response_code }} (?mTLS) ({{ cluster }})"
      },
      {
       "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$primary\", reporter=\"source\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster,destination_service, response_code), 0.001)",
       "legendFormat": "{{ destination_service }} : {{ response_code }} ({{ cluster }})"
      }
     ]
    },
    {
     "title": "Canary: Outgoing Requests by Destination And Response Code",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$canary\", reporter=\"source\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster,destination_service, response_code), 0.001)",
       "legendFormat": "{{ destination_service }} : {{ response_code }} (?mTLS) ({{ cluster }})"
      },
      {
       "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$canary\", reporter=\"source\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) by (cluster,destination_service, response_code), 0.001)",
       "legendFormat": "{{ destination_service }} : {{ response_code }} ({{ cluster }})"
      }
     ]
    }
   ]
  },
  {
   "title": "Utilization, Saturation, Errors (USE)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Primary: App CPU Usage (Avg all PODs, excludes Istio proxy)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by (cluster)(rate(container_cpu_usage_seconds_total{cpu=\"total\",namespace=\"$namespace\",pod=~\"$primary.*\", container!~\"POD|istio-proxy\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) * 100)",
       "legendFormat": "Average CPU Usage ({{ cluster }})"
      },
      {
       "expr": "kube_horizontalpodautoscaler_spec_target_metric{namespace=\"$namespace\",horizontalpodautoscaler=\"$namespace-hpa\",account=~\"$awsaccount\",cluster=~\"$cluster\"}",
       "legendFormat": "Target Metric for $namespace-hpa ({{ cluster }})"
      }
     ]
    },
    {
     "title": "Canary: App CPU Usage (Avg all PODs, excludes Istio proxy)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by (cluster)(rate(container_cpu_usage_seconds_total{cpu=\"total\",namespace=\"$namespace\",pod=~\"$canary.*\", pod!~\"$primary.*\", container!~\"POD|istio-proxy\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) * 100)",
       "legendFormat": "Average CPU Usage ({{ cluster }})"
      },
      {
       "expr": "kube_horizontalpodautoscaler_spec_target_metric{namespace=\"$namespace\",horizontalpodautoscaler=\"$namespace-canary-hpa\",account=~\"$awsaccount\",cluster=~\"$cluster\"}",
       "legendFormat": "Target Metric for $namespace-hpa ({{ cluster }})"
      }
     ]
    },
    {
     "title": "Primary: Max POD Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (cluster)(sum by (cluster,pod) (container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$primary.*\", container!~\"POD|istio-proxy\",account=~\"$awsaccount\",cluster=~\"$cluster\"}))",
       "legendFormat": "Max Memory Usage ({{ cluster }})"
      },
      {
       "expr": "max by (cluster)(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\"$primary.*\", container!~\"POD|istio-proxy\",account=~\"$awsaccount\",cluster=~\"$cluster\"})",
       "legendFormat": "Memory Request ({{ cluster }})"
      },
      {
       "expr": "max by (cluster)(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\"$primary.*\", container!~\"POD|istio-proxy\",account=~\"$awsaccount\",cluster=~\"$cluster\"})",
       "legendFormat": "Memory Limit ({{ cluster }})"
      }
     ]
    },
    {
     "title": "Canary: Max POD Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (cluster)(sum by (cluster,pod) (container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"$canary.*\", pod!~\"$primary.*\", container!~\"POD|istio-proxy\",account=~\"$awsaccount\",cluster=~\"$cluster\"}))",
       "legendFormat": "Max Memory Usage ({{ cluster }})"
      },
      {
       "expr": "max by (cluster)(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\"$canary.*\", pod!~\"$primary.*\", container!~\"POD|istio-proxy\",account=~\"$awsaccount\",cluster=~\"$cluster\"})",
       "legendFormat": "Memory Request ({{ cluster }})"
      },
      {
       "expr": "max by (cluster)(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\"$canary.*\", pod!~\"$primary.*\", container!~\"POD|istio-proxy\",account=~\"$awsaccount\",cluster=~\"$cluster\"})",
       "legendFormat": "Memory Limit ({{ cluster }})"
      }
     ]
    },
    {
     "title": "Primary: Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (cluster)(rate (container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$primary.*\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) ",
       "legendFormat": "received ({{ cluster }})"
      },
      {
       "expr": "-sum by (cluster)(rate (container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"$primary.*\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "-transmited ({{ cluster }})"
      }
     ]
    },
    {
     "title": "Canary: Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (cluster)(rate (container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$canary.*\",pod!~\"$primary.*\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) ",
       "legendFormat": "received ({{ cluster }})"
      },
      {
       "expr": "-sum by (cluster)(rate (container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"$canary.*\",pod!~\"$primary.*\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "-transmited ({{ cluster }})"
      }
     ]
    },
    {
     "title": "Primary: Disk I/O (IOPS)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (cluster)(rate (container_fs_reads_total{namespace=\"$namespace\",pod=~\"$primary.*\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) ",
       "legendFormat": "read ({{ cluster }})"
      },
      {
       "expr": "-sum by (cluster)(rate (container_fs_writes_total{namespace=\"$namespace\",pod=~\"$primary.*\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) ",
       "legendFormat": "-write ({{ cluster }})"
      }
     ]
    },
    {
     "title": "Canary: Disk I/O (IOPS)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (cluster)(rate (container_fs_reads_total{namespace=\"$namespace\",pod=~\"$canary.*\",pod!~\"$primary.*\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) ",
       "legendFormat": "read ({{ cluster }})"
      },
      {
       "expr": "-sum by (cluster)(rate (container_fs_writes_total{namespace=\"$namespace\",pod=~\"$canary.*\",pod!~\"$primary.*\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval])) ",
       "legendFormat": "-write ({{ cluster }})"
      }
     ]
    }
   ]
  },
  {
   "title": "Infrastructure Resources and Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Primary: Node & AZ Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(count(count(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$primary-.*\",container!~\"POD|istio-proxy\",account=~\"$awsaccount\",cluster=~\"$cluster\"}) by (cluster,instance,node_type,node_kubernetes_io_instance_type,failure_domain_beta_kubernetes_io_zone)) by (cluster,instance,node_type,node_kubernetes_io_instance_type,failure_domain_beta_kubernetes_io_zone)) by (cluster,node_type,failure_domain_beta_kubernetes_io_zone)",
       "legendFormat": "{{ failure_domain_beta_kubernetes_io_zone }} - {{node_type}} ({{ cluster }})"
      }
     ]
    },
    {
     "title": "Canary: Node & AZ Distribution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum(count(count(container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"$canary-.*\",pod!~\".*primary.*\",container!~\"POD|istio-proxy\",account=~\"$awsaccount\",cluster=~\"$cluster\"}) by (cluster,instance,node_type,node_kubernetes_io_instance_type,failure_domain_beta_kubernetes_io_zone)) by (cluster,instance,node_type,node_kubernetes_io_instance_type,failure_domain_beta_kubernetes_io_zone)) by (cluster,node_type,failure_domain_beta_kubernetes_io_zone)",
       "legendFormat": "{{ failure_domain_beta_kubernetes_io_zone }} - {{node_type}} ({{ cluster }})"
      }
     ]
    },
    {
     "title": "Primary: Workload Replicas (PODs)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=\"$namespace\",horizontalpodautoscaler=~\"$primary\",account=~\"$awsaccount\",cluster=~\"$cluster\"}",
       "legendFormat": "{{ horizontalpodautoscaler }} Healthy ({{ cluster }})"
      },
      {
       "expr": "kube_horizontalpodautoscaler_status_desired_replicas{namespace=\"$namespace\",horizontalpodautoscaler=~\"$primary\",account=~\"$awsaccount\",cluster=~\"$cluster\"}",
       "legendFormat": "{{ horizontalpodautoscaler }} Desired ({{ cluster }})"
      },
      {
       "expr": "kube_horizontalpodautoscaler_spec_min_replicas{namespace=\"$namespace\",horizontalpodautoscaler=~\"$primary\",account=~\"$awsaccount\",cluster=~\"$cluster\"}",
       "legendFormat": "{{ horizontalpodautoscaler }} Minimum ({{ cluster }})"
      },
      {
       "expr": "kube_horizontalpodautoscaler_spec_max_replicas{namespace=\"$namespace\",horizontalpodautoscaler=~\"$primary\",account=~\"$awsaccount\",cluster=~\"$cluster\"}",
       "legendFormat": "{{ horizontalpodautoscaler }} Maximum ({{ cluster }})"
      },
      {
       "expr": "kube_deployment_status_replicas_unavailable{namespace=\"$namespace\",deployment=\"$primary\",account=~\"$awsaccount\",cluster=~\"$cluster\"}",
       "legendFormat": "{{ deployment }} Not Ready ({{ cluster }})"
      }
     ]
    },
    {
     "title": "Canary: Workload Replicas (PODs)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=\"$namespace\",horizontalpodautoscaler=~\"$canary\",account=~\"$awsaccount\",cluster=~\"$cluster\"}",
       "legendFormat": "{{ horizontalpodautoscaler }} Healthy ({{ cluster }})"
      },
      {
       "expr": "kube_horizontalpodautoscaler_spec_min_replicas{namespace=\"$namespace\",horizontalpodautoscaler=~\"$canary\",account=~\"$awsaccount\",cluster=~\"$cluster\"}",
       "legendFormat": "{{ horizontalpodautoscaler }} Minimum ({{ cluster }})"
      },
      {
       "expr": "kube_horizontalpodautoscaler_spec_max_replicas{namespace=\"$namespace\",horizontalpodautoscaler=~\"$canary\",account=~\"$awsaccount\",cluster=~\"$cluster\"}",
       "legendFormat": "{{ horizontalpodautoscaler }} Maximum ({{ cluster }})"
      },
      {
       "expr": "kube_deployment_status_replicas_unavailable{namespace=\"$namespace\",deployment=\"$canary\",account=~\"$awsaccount\",cluster=~\"$cluster\"}",
       "legendFormat": "{{ deployment }} Not Ready"
      }
     ]
    },
    {
     "title": "Primary: PODs by replicaSet",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(kube_replicaset_status_ready_replicas{namespace=\"$namespace\",replicaset=~\"$primary-.*\",account=~\"$awsaccount\",cluster=~\"$cluster\"}) by (cluster,replicaset)",
       "legendFormat": "{{ replicaset }} ({{ cluster }})"
      }
     ]
    },
    {
     "title": "Canary: PODs by replicaSet",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(kube_replicaset_status_ready_replicas{namespace=\"$namespace\",replicaset=~\"$canary-.*\",replicaset!~\".*primary.*\",account=~\"$awsaccount\",cluster=~\"$cluster\"}) by (cluster,replicaset)",
       "legendFormat": "{{ replicaset }} ({{ cluster }})"
      }
     ]
    },
    {
     "title": "Primary: CPU Throttling",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (cluster)(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\",pod=~\"$primary-.*\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Average Throttle Rate ({{ cluster }})"
      }
     ]
    },
    {
     "title": "Canary: CPU Throttling",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (cluster)(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\",pod=~\"$canary-.*\",pod!~\".*primary.*\",account=~\"$awsaccount\",cluster=~\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "Average Throttle Rate ({{ cluster }})"
      }
     ]
    }
   ]
  }
 ]
}